version = "3.8.4"
runner.dialect = scala3

# Límites y alineación
maxColumn = 120
align.preset = more 

# Adopción de la sintaxis moderna de Scala 3
rewrite.scala3.convertToNewSyntax = true
rewrite.scala3.removeOptionalBraces = yes
rewrite.scala3.insertEndMarkerMinLines = 20

# Reglas de reescritura generales
rewrite.rules = [
  RedundantBraces,
  RedundantParens,
  SortModifiers,
  PreferCurlyFors,
  Imports
]

# Orden de los modificadores (ej. implicit private final val)
rewrite.sortModifiers.order = [
  "implicit", "inline", "opaque", "override", "private", "protected", "final", "sealed", "abstract", "lazy"
]

# Agrupación y ordenación automática de imports
rewrite.imports.sort = scalastyle
rewrite.imports.groups = [
  ["java\\..*", "scala\\..*"],
  ["org\\.apache\\.pekko\\..*"],
  ["io\\.circe\\..*"],
  ["es\\..*"] # Tu package local
]